---
title: "ECO1018 (seminar 2)"
author: "Edu Gonzalo Almorox"
date: "e.gonzalo-almorox@newcastle.ac.uk"
output:
  beamer_presentation:
  incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Question 1: Consumer choice 

Consider Nick. Apart from being a wannabe-nightclub-owner, Nick also has a bit of a dull taste in food. He essentially only eats Pies (just pies, no mash etc.) and Chinese take-away. Pies costs £2.5, while his favourite Chinese take-away sells meals for £5. Nick currently has £1,000 to spend for food each month.

- 1. Draw Nick’s budget constraint.
- 2. What is Nick’s optimal choice if (a) he considers pies and chinese take-aways to be perfect substitutes and (b) he prefers a bit of variety in his food?
- 3. The price of Chinese take-away meals drops to £1. How does this affect his choice under (a) and (b)?
- 4. The price of Chinese take-away increases back to £5 per meal. At the same time, Nick (who has decided to become a professional sumo wrestler and needs to gain weight) increases the amount of money he spends on food each month to £10,000 per month. How does this affect his choice under (a) and (b)?

## Question 2: Individual and market demand

Table 1 presents the annual demand for Newcastle United football shirts for both club members and non-members. Draw the annual demand curve for each of the two groups and the annual market demand.

| Price (£)  | Members       | Non-Members|Market
|----------- |---------------|------------|-------
|  80        |  24           |  4         | 28
|  65        |  26           |  5         | 31
|  50        |  28           |  6         | 34
|  35        |  30           |  7         | 37 
|  20        |  32           |  87        | 119

## Question 3: Market demand 


Assume that the market for cigarettes consists of two groups of consumers – heavy and light smokers. The government attempts to reduce the overall amount of smoking in society and introduced direct price control laws after nationalising the tobacco industry (i.e., the government sets the price and takes over all the tobacco firms). The daily demand for light and heavy smokers is given in table 2. 

| Price (£)  | Heavy smokers | Light smokers |Market
|------------|---------------|---------------|-------
|  0.1        |  5           |  5            | 10
|  0.2        |  5           |  4.5          | 9.5
|  0.3        |  5           |  4            | 9
|  0.4        |  5           |  3            | 8 
|  0.5        |  4.5         |  1            | 5.5
|  0.6        |  4           |  0            | 4
|  1          |  3           |  0            | 3

## Question 3: Market demand 

- 1 Draw the demand curve for each of the two groups and the market demand. 
- 2 Is a change from a price of 0.3 to 0.4 structurally different from a change from 0.5 to 0.6?
